name: test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rust
    steps:
      - uses: actions/checkout@v2
      - run: cargo build
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo audit
      - run: cargo test
